// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cura.proto

#ifndef PROTOBUF_Cura_2eproto__INCLUDED
#define PROTOBUF_Cura_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>


#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Cura {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Cura_2eproto();
void protobuf_AssignDesc_Cura_2eproto();
void protobuf_ShutdownFile_Cura_2eproto();

class ObjectList;
class Object;
class Progress;
class SlicedObjectList;
class SlicedObject;
class Layer;
class Polygon;
class GCodeLayer;
class ObjectPrintTime;
class SettingList;
class Setting;
class GCodePrefix;

enum Polygon_Type {
  Polygon_Type_NoneType = 0,
  Polygon_Type_Inset0Type = 1,
  Polygon_Type_InsetXType = 2,
  Polygon_Type_SkinType = 3,
  Polygon_Type_SupportType = 4,
  Polygon_Type_SkirtType = 5,
  Polygon_Type_Polygon_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Polygon_Type_Polygon_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Polygon_Type_IsValid(int value);
const Polygon_Type Polygon_Type_Type_MIN = Polygon_Type_NoneType;
const Polygon_Type Polygon_Type_Type_MAX = Polygon_Type_SkirtType;
const int Polygon_Type_Type_ARRAYSIZE = Polygon_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Polygon_Type_descriptor();
inline const ::std::string& Polygon_Type_Name(Polygon_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Polygon_Type_descriptor(), value);
}
inline bool Polygon_Type_Parse(
    const ::std::string& name, Polygon_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Polygon_Type>(
    Polygon_Type_descriptor(), name, value);
}
// ===================================================================

class ObjectList : public ::google::protobuf::Message {
 public:
  ObjectList();
  virtual ~ObjectList();

  ObjectList(const ObjectList& from);

  inline ObjectList& operator=(const ObjectList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectList& default_instance();

  void Swap(ObjectList* other);

  // implements Message ----------------------------------------------

  inline ObjectList* New() const { return New(NULL); }

  ObjectList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectList& from);
  void MergeFrom(const ObjectList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ObjectList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Cura.Object objects = 1;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 1;
  inline const ::Cura::Object& objects(int index) const;
  inline ::Cura::Object* mutable_objects(int index);
  inline ::Cura::Object* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::Cura::Object >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::Cura::Object >*
      mutable_objects();

  // @@protoc_insertion_point(class_scope:Cura.ObjectList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Cura::Object > objects_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static ObjectList* default_instance_;
};
// -------------------------------------------------------------------

class Object : public ::google::protobuf::Message {
 public:
  Object();
  virtual ~Object();

  Object(const Object& from);

  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Object& default_instance();

  void Swap(Object* other);

  // implements Message ----------------------------------------------

  inline Object* New() const { return New(NULL); }

  Object* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Object* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // optional bytes vertices = 2;
  inline void clear_vertices();
  static const int kVerticesFieldNumber = 2;
  inline const ::std::string& vertices() const;
  inline void set_vertices(const ::std::string& value);
  inline void set_vertices(const char* value);
  inline void set_vertices(const void* value, size_t size);
  inline ::std::string* mutable_vertices();
  inline ::std::string* release_vertices();
  inline void set_allocated_vertices(::std::string* vertices);

  // optional bytes normals = 3;
  inline void clear_normals();
  static const int kNormalsFieldNumber = 3;
  inline const ::std::string& normals() const;
  inline void set_normals(const ::std::string& value);
  inline void set_normals(const char* value);
  inline void set_normals(const void* value, size_t size);
  inline ::std::string* mutable_normals();
  inline ::std::string* release_normals();
  inline void set_allocated_normals(::std::string* normals);

  // optional bytes indices = 4;
  inline void clear_indices();
  static const int kIndicesFieldNumber = 4;
  inline const ::std::string& indices() const;
  inline void set_indices(const ::std::string& value);
  inline void set_indices(const char* value);
  inline void set_indices(const void* value, size_t size);
  inline ::std::string* mutable_indices();
  inline ::std::string* release_indices();
  inline void set_allocated_indices(::std::string* indices);

  // repeated .Cura.Setting settings = 5;
  inline int settings_size() const;
  inline void clear_settings();
  static const int kSettingsFieldNumber = 5;
  inline const ::Cura::Setting& settings(int index) const;
  inline ::Cura::Setting* mutable_settings(int index);
  inline ::Cura::Setting* add_settings();
  inline const ::google::protobuf::RepeatedPtrField< ::Cura::Setting >&
      settings() const;
  inline ::google::protobuf::RepeatedPtrField< ::Cura::Setting >*
      mutable_settings();

  // @@protoc_insertion_point(class_scope:Cura.Object)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::internal::ArenaStringPtr vertices_;
  ::google::protobuf::internal::ArenaStringPtr normals_;
  ::google::protobuf::internal::ArenaStringPtr indices_;
  ::google::protobuf::RepeatedPtrField< ::Cura::Setting > settings_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static Object* default_instance_;
};
// -------------------------------------------------------------------

class Progress : public ::google::protobuf::Message {
 public:
  Progress();
  virtual ~Progress();

  Progress(const Progress& from);

  inline Progress& operator=(const Progress& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Progress& default_instance();

  void Swap(Progress* other);

  // implements Message ----------------------------------------------

  inline Progress* New() const { return New(NULL); }

  Progress* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Progress& from);
  void MergeFrom(const Progress& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Progress* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float amount = 1;
  inline void clear_amount();
  static const int kAmountFieldNumber = 1;
  inline float amount() const;
  inline void set_amount(float value);

  // @@protoc_insertion_point(class_scope:Cura.Progress)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float amount_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static Progress* default_instance_;
};
// -------------------------------------------------------------------

class SlicedObjectList : public ::google::protobuf::Message {
 public:
  SlicedObjectList();
  virtual ~SlicedObjectList();

  SlicedObjectList(const SlicedObjectList& from);

  inline SlicedObjectList& operator=(const SlicedObjectList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SlicedObjectList& default_instance();

  void Swap(SlicedObjectList* other);

  // implements Message ----------------------------------------------

  inline SlicedObjectList* New() const { return New(NULL); }

  SlicedObjectList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SlicedObjectList& from);
  void MergeFrom(const SlicedObjectList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SlicedObjectList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Cura.SlicedObject objects = 1;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 1;
  inline const ::Cura::SlicedObject& objects(int index) const;
  inline ::Cura::SlicedObject* mutable_objects(int index);
  inline ::Cura::SlicedObject* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::Cura::SlicedObject >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::Cura::SlicedObject >*
      mutable_objects();

  // @@protoc_insertion_point(class_scope:Cura.SlicedObjectList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Cura::SlicedObject > objects_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static SlicedObjectList* default_instance_;
};
// -------------------------------------------------------------------

class SlicedObject : public ::google::protobuf::Message {
 public:
  SlicedObject();
  virtual ~SlicedObject();

  SlicedObject(const SlicedObject& from);

  inline SlicedObject& operator=(const SlicedObject& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SlicedObject& default_instance();

  void Swap(SlicedObject* other);

  // implements Message ----------------------------------------------

  inline SlicedObject* New() const { return New(NULL); }

  SlicedObject* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SlicedObject& from);
  void MergeFrom(const SlicedObject& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SlicedObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // repeated .Cura.Layer layers = 2;
  inline int layers_size() const;
  inline void clear_layers();
  static const int kLayersFieldNumber = 2;
  inline const ::Cura::Layer& layers(int index) const;
  inline ::Cura::Layer* mutable_layers(int index);
  inline ::Cura::Layer* add_layers();
  inline const ::google::protobuf::RepeatedPtrField< ::Cura::Layer >&
      layers() const;
  inline ::google::protobuf::RepeatedPtrField< ::Cura::Layer >*
      mutable_layers();

  // @@protoc_insertion_point(class_scope:Cura.SlicedObject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::RepeatedPtrField< ::Cura::Layer > layers_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static SlicedObject* default_instance_;
};
// -------------------------------------------------------------------

class Layer : public ::google::protobuf::Message {
 public:
  Layer();
  virtual ~Layer();

  Layer(const Layer& from);

  inline Layer& operator=(const Layer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Layer& default_instance();

  void Swap(Layer* other);

  // implements Message ----------------------------------------------

  inline Layer* New() const { return New(NULL); }

  Layer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Layer& from);
  void MergeFrom(const Layer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Layer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // repeated .Cura.Polygon polygons = 2;
  inline int polygons_size() const;
  inline void clear_polygons();
  static const int kPolygonsFieldNumber = 2;
  inline const ::Cura::Polygon& polygons(int index) const;
  inline ::Cura::Polygon* mutable_polygons(int index);
  inline ::Cura::Polygon* add_polygons();
  inline const ::google::protobuf::RepeatedPtrField< ::Cura::Polygon >&
      polygons() const;
  inline ::google::protobuf::RepeatedPtrField< ::Cura::Polygon >*
      mutable_polygons();

  // @@protoc_insertion_point(class_scope:Cura.Layer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Cura::Polygon > polygons_;
  ::google::protobuf::int32 id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static Layer* default_instance_;
};
// -------------------------------------------------------------------

class Polygon : public ::google::protobuf::Message {
 public:
  Polygon();
  virtual ~Polygon();

  Polygon(const Polygon& from);

  inline Polygon& operator=(const Polygon& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Polygon& default_instance();

  void Swap(Polygon* other);

  // implements Message ----------------------------------------------

  inline Polygon* New() const { return New(NULL); }

  Polygon* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Polygon& from);
  void MergeFrom(const Polygon& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Polygon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Polygon_Type Type;
  static const Type NoneType = Polygon_Type_NoneType;
  static const Type Inset0Type = Polygon_Type_Inset0Type;
  static const Type InsetXType = Polygon_Type_InsetXType;
  static const Type SkinType = Polygon_Type_SkinType;
  static const Type SupportType = Polygon_Type_SupportType;
  static const Type SkirtType = Polygon_Type_SkirtType;
  static inline bool Type_IsValid(int value) {
    return Polygon_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Polygon_Type_Type_MIN;
  static const Type Type_MAX =
    Polygon_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Polygon_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Polygon_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Polygon_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Polygon_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .Cura.Polygon.Type type = 1;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Cura::Polygon_Type type() const;
  inline void set_type(::Cura::Polygon_Type value);

  // optional bytes points = 2;
  inline void clear_points();
  static const int kPointsFieldNumber = 2;
  inline const ::std::string& points() const;
  inline void set_points(const ::std::string& value);
  inline void set_points(const char* value);
  inline void set_points(const void* value, size_t size);
  inline ::std::string* mutable_points();
  inline ::std::string* release_points();
  inline void set_allocated_points(::std::string* points);

  // @@protoc_insertion_point(class_scope:Cura.Polygon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr points_;
  int type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static Polygon* default_instance_;
};
// -------------------------------------------------------------------

class GCodeLayer : public ::google::protobuf::Message {
 public:
  GCodeLayer();
  virtual ~GCodeLayer();

  GCodeLayer(const GCodeLayer& from);

  inline GCodeLayer& operator=(const GCodeLayer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCodeLayer& default_instance();

  void Swap(GCodeLayer* other);

  // implements Message ----------------------------------------------

  inline GCodeLayer* New() const { return New(NULL); }

  GCodeLayer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCodeLayer& from);
  void MergeFrom(const GCodeLayer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GCodeLayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // optional bytes data = 2;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:Cura.GCodeLayer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static GCodeLayer* default_instance_;
};
// -------------------------------------------------------------------

class ObjectPrintTime : public ::google::protobuf::Message {
 public:
  ObjectPrintTime();
  virtual ~ObjectPrintTime();

  ObjectPrintTime(const ObjectPrintTime& from);

  inline ObjectPrintTime& operator=(const ObjectPrintTime& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectPrintTime& default_instance();

  void Swap(ObjectPrintTime* other);

  // implements Message ----------------------------------------------

  inline ObjectPrintTime* New() const { return New(NULL); }

  ObjectPrintTime* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectPrintTime& from);
  void MergeFrom(const ObjectPrintTime& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ObjectPrintTime* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // optional float time = 2;
  inline void clear_time();
  static const int kTimeFieldNumber = 2;
  inline float time() const;
  inline void set_time(float value);

  // optional float material_amount = 3;
  inline void clear_material_amount();
  static const int kMaterialAmountFieldNumber = 3;
  inline float material_amount() const;
  inline void set_material_amount(float value);

  // @@protoc_insertion_point(class_scope:Cura.ObjectPrintTime)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 id_;
  float time_;
  float material_amount_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static ObjectPrintTime* default_instance_;
};
// -------------------------------------------------------------------

class SettingList : public ::google::protobuf::Message {
 public:
  SettingList();
  virtual ~SettingList();

  SettingList(const SettingList& from);

  inline SettingList& operator=(const SettingList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SettingList& default_instance();

  void Swap(SettingList* other);

  // implements Message ----------------------------------------------

  inline SettingList* New() const { return New(NULL); }

  SettingList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SettingList& from);
  void MergeFrom(const SettingList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SettingList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Cura.Setting settings = 1;
  inline int settings_size() const;
  inline void clear_settings();
  static const int kSettingsFieldNumber = 1;
  inline const ::Cura::Setting& settings(int index) const;
  inline ::Cura::Setting* mutable_settings(int index);
  inline ::Cura::Setting* add_settings();
  inline const ::google::protobuf::RepeatedPtrField< ::Cura::Setting >&
      settings() const;
  inline ::google::protobuf::RepeatedPtrField< ::Cura::Setting >*
      mutable_settings();

  // @@protoc_insertion_point(class_scope:Cura.SettingList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Cura::Setting > settings_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static SettingList* default_instance_;
};
// -------------------------------------------------------------------

class Setting : public ::google::protobuf::Message {
 public:
  Setting();
  virtual ~Setting();

  Setting(const Setting& from);

  inline Setting& operator=(const Setting& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Setting& default_instance();

  void Swap(Setting* other);

  // implements Message ----------------------------------------------

  inline Setting* New() const { return New(NULL); }

  Setting* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Setting& from);
  void MergeFrom(const Setting& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Setting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional bytes value = 2;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const void* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:Cura.Setting)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static Setting* default_instance_;
};
// -------------------------------------------------------------------

class GCodePrefix : public ::google::protobuf::Message {
 public:
  GCodePrefix();
  virtual ~GCodePrefix();

  GCodePrefix(const GCodePrefix& from);

  inline GCodePrefix& operator=(const GCodePrefix& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GCodePrefix& default_instance();

  void Swap(GCodePrefix* other);

  // implements Message ----------------------------------------------

  inline GCodePrefix* New() const { return New(NULL); }

  GCodePrefix* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GCodePrefix& from);
  void MergeFrom(const GCodePrefix& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GCodePrefix* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 2;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:Cura.GCodePrefix)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Cura_2eproto();
  friend void protobuf_AssignDesc_Cura_2eproto();
  friend void protobuf_ShutdownFile_Cura_2eproto();

  void InitAsDefaultInstance();
  static GCodePrefix* default_instance_;
};
// ===================================================================


// ===================================================================

// ObjectList

// repeated .Cura.Object objects = 1;
inline int ObjectList::objects_size() const {
  return objects_.size();
}
inline void ObjectList::clear_objects() {
  objects_.Clear();
}
inline const ::Cura::Object& ObjectList::objects(int index) const {
  // @@protoc_insertion_point(field_get:Cura.ObjectList.objects)
  return objects_.Get(index);
}
inline ::Cura::Object* ObjectList::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:Cura.ObjectList.objects)
  return objects_.Mutable(index);
}
inline ::Cura::Object* ObjectList::add_objects() {
  // @@protoc_insertion_point(field_add:Cura.ObjectList.objects)
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Cura::Object >&
ObjectList::objects() const {
  // @@protoc_insertion_point(field_list:Cura.ObjectList.objects)
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::Cura::Object >*
ObjectList::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:Cura.ObjectList.objects)
  return &objects_;
}

// -------------------------------------------------------------------

// Object

// optional int64 id = 1;
inline void Object::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Object::id() const {
  // @@protoc_insertion_point(field_get:Cura.Object.id)
  return id_;
}
inline void Object::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Cura.Object.id)
}

// optional bytes vertices = 2;
inline void Object::clear_vertices() {
  vertices_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Object::vertices() const {
  // @@protoc_insertion_point(field_get:Cura.Object.vertices)
  return vertices_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_vertices(const ::std::string& value) {
  
  vertices_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.Object.vertices)
}
inline void Object::set_vertices(const char* value) {
  
  vertices_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.Object.vertices)
}
inline void Object::set_vertices(const void* value, size_t size) {
  
  vertices_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.Object.vertices)
}
inline ::std::string* Object::mutable_vertices() {
  
  // @@protoc_insertion_point(field_mutable:Cura.Object.vertices)
  return vertices_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Object::release_vertices() {
  
  return vertices_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_allocated_vertices(::std::string* vertices) {
  if (vertices != NULL) {
    
  } else {
    
  }
  vertices_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), vertices);
  // @@protoc_insertion_point(field_set_allocated:Cura.Object.vertices)
}

// optional bytes normals = 3;
inline void Object::clear_normals() {
  normals_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Object::normals() const {
  // @@protoc_insertion_point(field_get:Cura.Object.normals)
  return normals_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_normals(const ::std::string& value) {
  
  normals_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.Object.normals)
}
inline void Object::set_normals(const char* value) {
  
  normals_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.Object.normals)
}
inline void Object::set_normals(const void* value, size_t size) {
  
  normals_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.Object.normals)
}
inline ::std::string* Object::mutable_normals() {
  
  // @@protoc_insertion_point(field_mutable:Cura.Object.normals)
  return normals_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Object::release_normals() {
  
  return normals_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_allocated_normals(::std::string* normals) {
  if (normals != NULL) {
    
  } else {
    
  }
  normals_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), normals);
  // @@protoc_insertion_point(field_set_allocated:Cura.Object.normals)
}

// optional bytes indices = 4;
inline void Object::clear_indices() {
  indices_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Object::indices() const {
  // @@protoc_insertion_point(field_get:Cura.Object.indices)
  return indices_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_indices(const ::std::string& value) {
  
  indices_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.Object.indices)
}
inline void Object::set_indices(const char* value) {
  
  indices_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.Object.indices)
}
inline void Object::set_indices(const void* value, size_t size) {
  
  indices_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.Object.indices)
}
inline ::std::string* Object::mutable_indices() {
  
  // @@protoc_insertion_point(field_mutable:Cura.Object.indices)
  return indices_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Object::release_indices() {
  
  return indices_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_allocated_indices(::std::string* indices) {
  if (indices != NULL) {
    
  } else {
    
  }
  indices_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), indices);
  // @@protoc_insertion_point(field_set_allocated:Cura.Object.indices)
}

// repeated .Cura.Setting settings = 5;
inline int Object::settings_size() const {
  return settings_.size();
}
inline void Object::clear_settings() {
  settings_.Clear();
}
inline const ::Cura::Setting& Object::settings(int index) const {
  // @@protoc_insertion_point(field_get:Cura.Object.settings)
  return settings_.Get(index);
}
inline ::Cura::Setting* Object::mutable_settings(int index) {
  // @@protoc_insertion_point(field_mutable:Cura.Object.settings)
  return settings_.Mutable(index);
}
inline ::Cura::Setting* Object::add_settings() {
  // @@protoc_insertion_point(field_add:Cura.Object.settings)
  return settings_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Cura::Setting >&
Object::settings() const {
  // @@protoc_insertion_point(field_list:Cura.Object.settings)
  return settings_;
}
inline ::google::protobuf::RepeatedPtrField< ::Cura::Setting >*
Object::mutable_settings() {
  // @@protoc_insertion_point(field_mutable_list:Cura.Object.settings)
  return &settings_;
}

// -------------------------------------------------------------------

// Progress

// optional float amount = 1;
inline void Progress::clear_amount() {
  amount_ = 0;
}
inline float Progress::amount() const {
  // @@protoc_insertion_point(field_get:Cura.Progress.amount)
  return amount_;
}
inline void Progress::set_amount(float value) {
  
  amount_ = value;
  // @@protoc_insertion_point(field_set:Cura.Progress.amount)
}

// -------------------------------------------------------------------

// SlicedObjectList

// repeated .Cura.SlicedObject objects = 1;
inline int SlicedObjectList::objects_size() const {
  return objects_.size();
}
inline void SlicedObjectList::clear_objects() {
  objects_.Clear();
}
inline const ::Cura::SlicedObject& SlicedObjectList::objects(int index) const {
  // @@protoc_insertion_point(field_get:Cura.SlicedObjectList.objects)
  return objects_.Get(index);
}
inline ::Cura::SlicedObject* SlicedObjectList::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:Cura.SlicedObjectList.objects)
  return objects_.Mutable(index);
}
inline ::Cura::SlicedObject* SlicedObjectList::add_objects() {
  // @@protoc_insertion_point(field_add:Cura.SlicedObjectList.objects)
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Cura::SlicedObject >&
SlicedObjectList::objects() const {
  // @@protoc_insertion_point(field_list:Cura.SlicedObjectList.objects)
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::Cura::SlicedObject >*
SlicedObjectList::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:Cura.SlicedObjectList.objects)
  return &objects_;
}

// -------------------------------------------------------------------

// SlicedObject

// optional int64 id = 1;
inline void SlicedObject::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 SlicedObject::id() const {
  // @@protoc_insertion_point(field_get:Cura.SlicedObject.id)
  return id_;
}
inline void SlicedObject::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Cura.SlicedObject.id)
}

// repeated .Cura.Layer layers = 2;
inline int SlicedObject::layers_size() const {
  return layers_.size();
}
inline void SlicedObject::clear_layers() {
  layers_.Clear();
}
inline const ::Cura::Layer& SlicedObject::layers(int index) const {
  // @@protoc_insertion_point(field_get:Cura.SlicedObject.layers)
  return layers_.Get(index);
}
inline ::Cura::Layer* SlicedObject::mutable_layers(int index) {
  // @@protoc_insertion_point(field_mutable:Cura.SlicedObject.layers)
  return layers_.Mutable(index);
}
inline ::Cura::Layer* SlicedObject::add_layers() {
  // @@protoc_insertion_point(field_add:Cura.SlicedObject.layers)
  return layers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Cura::Layer >&
SlicedObject::layers() const {
  // @@protoc_insertion_point(field_list:Cura.SlicedObject.layers)
  return layers_;
}
inline ::google::protobuf::RepeatedPtrField< ::Cura::Layer >*
SlicedObject::mutable_layers() {
  // @@protoc_insertion_point(field_mutable_list:Cura.SlicedObject.layers)
  return &layers_;
}

// -------------------------------------------------------------------

// Layer

// optional int32 id = 1;
inline void Layer::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 Layer::id() const {
  // @@protoc_insertion_point(field_get:Cura.Layer.id)
  return id_;
}
inline void Layer::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Cura.Layer.id)
}

// repeated .Cura.Polygon polygons = 2;
inline int Layer::polygons_size() const {
  return polygons_.size();
}
inline void Layer::clear_polygons() {
  polygons_.Clear();
}
inline const ::Cura::Polygon& Layer::polygons(int index) const {
  // @@protoc_insertion_point(field_get:Cura.Layer.polygons)
  return polygons_.Get(index);
}
inline ::Cura::Polygon* Layer::mutable_polygons(int index) {
  // @@protoc_insertion_point(field_mutable:Cura.Layer.polygons)
  return polygons_.Mutable(index);
}
inline ::Cura::Polygon* Layer::add_polygons() {
  // @@protoc_insertion_point(field_add:Cura.Layer.polygons)
  return polygons_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Cura::Polygon >&
Layer::polygons() const {
  // @@protoc_insertion_point(field_list:Cura.Layer.polygons)
  return polygons_;
}
inline ::google::protobuf::RepeatedPtrField< ::Cura::Polygon >*
Layer::mutable_polygons() {
  // @@protoc_insertion_point(field_mutable_list:Cura.Layer.polygons)
  return &polygons_;
}

// -------------------------------------------------------------------

// Polygon

// optional .Cura.Polygon.Type type = 1;
inline void Polygon::clear_type() {
  type_ = 0;
}
inline ::Cura::Polygon_Type Polygon::type() const {
  // @@protoc_insertion_point(field_get:Cura.Polygon.type)
  return static_cast< ::Cura::Polygon_Type >(type_);
}
inline void Polygon::set_type(::Cura::Polygon_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Cura.Polygon.type)
}

// optional bytes points = 2;
inline void Polygon::clear_points() {
  points_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Polygon::points() const {
  // @@protoc_insertion_point(field_get:Cura.Polygon.points)
  return points_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Polygon::set_points(const ::std::string& value) {
  
  points_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.Polygon.points)
}
inline void Polygon::set_points(const char* value) {
  
  points_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.Polygon.points)
}
inline void Polygon::set_points(const void* value, size_t size) {
  
  points_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.Polygon.points)
}
inline ::std::string* Polygon::mutable_points() {
  
  // @@protoc_insertion_point(field_mutable:Cura.Polygon.points)
  return points_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Polygon::release_points() {
  
  return points_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Polygon::set_allocated_points(::std::string* points) {
  if (points != NULL) {
    
  } else {
    
  }
  points_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), points);
  // @@protoc_insertion_point(field_set_allocated:Cura.Polygon.points)
}

// -------------------------------------------------------------------

// GCodeLayer

// optional int64 id = 1;
inline void GCodeLayer::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GCodeLayer::id() const {
  // @@protoc_insertion_point(field_get:Cura.GCodeLayer.id)
  return id_;
}
inline void GCodeLayer::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Cura.GCodeLayer.id)
}

// optional bytes data = 2;
inline void GCodeLayer::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GCodeLayer::data() const {
  // @@protoc_insertion_point(field_get:Cura.GCodeLayer.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GCodeLayer::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.GCodeLayer.data)
}
inline void GCodeLayer::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.GCodeLayer.data)
}
inline void GCodeLayer::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.GCodeLayer.data)
}
inline ::std::string* GCodeLayer::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:Cura.GCodeLayer.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GCodeLayer::release_data() {
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GCodeLayer::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:Cura.GCodeLayer.data)
}

// -------------------------------------------------------------------

// ObjectPrintTime

// optional int64 id = 1;
inline void ObjectPrintTime::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ObjectPrintTime::id() const {
  // @@protoc_insertion_point(field_get:Cura.ObjectPrintTime.id)
  return id_;
}
inline void ObjectPrintTime::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Cura.ObjectPrintTime.id)
}

// optional float time = 2;
inline void ObjectPrintTime::clear_time() {
  time_ = 0;
}
inline float ObjectPrintTime::time() const {
  // @@protoc_insertion_point(field_get:Cura.ObjectPrintTime.time)
  return time_;
}
inline void ObjectPrintTime::set_time(float value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:Cura.ObjectPrintTime.time)
}

// optional float material_amount = 3;
inline void ObjectPrintTime::clear_material_amount() {
  material_amount_ = 0;
}
inline float ObjectPrintTime::material_amount() const {
  // @@protoc_insertion_point(field_get:Cura.ObjectPrintTime.material_amount)
  return material_amount_;
}
inline void ObjectPrintTime::set_material_amount(float value) {
  
  material_amount_ = value;
  // @@protoc_insertion_point(field_set:Cura.ObjectPrintTime.material_amount)
}

// -------------------------------------------------------------------

// SettingList

// repeated .Cura.Setting settings = 1;
inline int SettingList::settings_size() const {
  return settings_.size();
}
inline void SettingList::clear_settings() {
  settings_.Clear();
}
inline const ::Cura::Setting& SettingList::settings(int index) const {
  // @@protoc_insertion_point(field_get:Cura.SettingList.settings)
  return settings_.Get(index);
}
inline ::Cura::Setting* SettingList::mutable_settings(int index) {
  // @@protoc_insertion_point(field_mutable:Cura.SettingList.settings)
  return settings_.Mutable(index);
}
inline ::Cura::Setting* SettingList::add_settings() {
  // @@protoc_insertion_point(field_add:Cura.SettingList.settings)
  return settings_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Cura::Setting >&
SettingList::settings() const {
  // @@protoc_insertion_point(field_list:Cura.SettingList.settings)
  return settings_;
}
inline ::google::protobuf::RepeatedPtrField< ::Cura::Setting >*
SettingList::mutable_settings() {
  // @@protoc_insertion_point(field_mutable_list:Cura.SettingList.settings)
  return &settings_;
}

// -------------------------------------------------------------------

// Setting

// optional string name = 1;
inline void Setting::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Setting::name() const {
  // @@protoc_insertion_point(field_get:Cura.Setting.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Setting::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.Setting.name)
}
inline void Setting::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.Setting.name)
}
inline void Setting::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.Setting.name)
}
inline ::std::string* Setting::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Cura.Setting.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Setting::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Setting::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Cura.Setting.name)
}

// optional bytes value = 2;
inline void Setting::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Setting::value() const {
  // @@protoc_insertion_point(field_get:Cura.Setting.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Setting::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.Setting.value)
}
inline void Setting::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.Setting.value)
}
inline void Setting::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.Setting.value)
}
inline ::std::string* Setting::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:Cura.Setting.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Setting::release_value() {
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Setting::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:Cura.Setting.value)
}

// -------------------------------------------------------------------

// GCodePrefix

// optional bytes data = 2;
inline void GCodePrefix::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GCodePrefix::data() const {
  // @@protoc_insertion_point(field_get:Cura.GCodePrefix.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GCodePrefix::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cura.GCodePrefix.data)
}
inline void GCodePrefix::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cura.GCodePrefix.data)
}
inline void GCodePrefix::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cura.GCodePrefix.data)
}
inline ::std::string* GCodePrefix::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:Cura.GCodePrefix.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GCodePrefix::release_data() {
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GCodePrefix::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:Cura.GCodePrefix.data)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Cura

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Cura::Polygon_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Cura::Polygon_Type>() {
  return ::Cura::Polygon_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Cura_2eproto__INCLUDED
